/var/log/nginx/*.log {
    daily
    maxsize 5M
    rotate 3
    missingok
    notifempty
    compress
    sharedscripts
    postrotate
        systemctl kill -s USR1 nginx.service >/dev/null 2>&1 || true
    endscript
}
