"""Application-generated ULIDs.

The service uses strings rather than database-generated identifiers so IDs are
safe to create before a transaction and are identical across API and worker.
This small implementation avoids making model imports depend on a particular
ULID package while retaining the canonical 26-character Crockford encoding.
"""

from __future__ import annotations

import secrets
import time
from typing import Any

from sqlalchemy import CHAR
from sqlalchemy.types import TypeDecorator

ULID_LENGTH = 26
_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
_DECODE = {character: index for index, character in enumerate(_ALPHABET)}


def _encode_ulid(value: int) -> str:
    # 128 bits take 26 base32 digits (the first digit is constrained to 0-7).
    encoded = ["0"] * ULID_LENGTH
    for position in range(ULID_LENGTH - 1, -1, -1):
        encoded[position] = _ALPHABET[value & 0x1F]
        value >>= 5
    return "".join(encoded)


def new_ulid() -> str:
    """Return a canonical uppercase ULID generated by the application."""

    timestamp_ms = time.time_ns() // 1_000_000
    if timestamp_ms < 0 or timestamp_ms >= (1 << 48):
        raise ValueError("current time cannot be represented by a ULID")
    return _encode_ulid((timestamp_ms << 80) | secrets.randbits(80))


def is_valid_ulid(value: Any) -> bool:
    """Return whether *value* is a canonical, decodable ULID string."""

    if not isinstance(value, str) or len(value) != ULID_LENGTH:
        return False
    # Crockford's ULID representation is canonical uppercase.  Rejecting
    # ambiguous aliases keeps IDs byte-stable in URLs and database indexes.
    if value != value.upper():
        return False
    if value[0] not in "01234567":
        return False
    return all(character in _DECODE for character in value)


class ULIDType(TypeDecorator[str]):
    """A strict ``CHAR(26)`` SQLAlchemy type for application ULIDs."""

    impl = CHAR(ULID_LENGTH)
    cache_ok = True

    def process_bind_param(self, value: Any, dialect: Any) -> str | None:
        if value is None:
            return None
        # ``ulid-py`` returns a ULID object while this package's generator
        # returns a string; accepting its canonical string representation keeps
        # both call styles interoperable at the DB boundary.
        candidate = value if isinstance(value, str) else str(value)
        if not is_valid_ulid(candidate):
            raise ValueError("ULID values must be canonical 26-character strings")
        return candidate

    def process_result_value(self, value: Any, dialect: Any) -> str | None:
        return value
